/* Seed content ported from the design's data layer (English + Arabic). */

const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

const PRODUCTS = [
  { id: 'p1', cat: 'tshirt', name_en: 'Essential Cotton Tee', name_ar: 'تيشيرت قطن أساسي',
    price: 2400, oldPrice: null, isNew: true, rating: 4.8, sold: 312,
    colors: ['cream', 'clay', 'olive', 'ink'], sizes: SIZES,
    desc_en: 'Our heavy 220 gsm cotton with a straight cut and impeccable drape. The ultimate t-shirt to customize.',
    desc_ar: 'قطن ثقيل 220غ/م²، قصّة مستقيمة. التيشيرت المثالي للتخصيص.' },
  { id: 'p2', cat: 'tshirt', name_en: 'Boxy Oversized Tee', name_ar: 'تيشيرت أوفرسايز',
    price: 2900, oldPrice: 3400, isNew: true, rating: 4.7, sold: 188,
    colors: ['sand', 'ink', 'forest', 'blush'], sizes: SIZES,
    desc_en: 'Relaxed streetwear cut with dropped shoulders. Ideal for large back prints.',
    desc_ar: 'قصّة واسعة ستايل ستريت وير، أكتاف منسدلة.' },
  { id: 'p3', cat: 'tshirt', name_en: 'Slim Crewneck Tee', name_ar: 'تيشيرت ضيّق',
    price: 2200, oldPrice: null, isNew: false, rating: 4.6, sold: 421,
    colors: ['white', 'navy', 'clay', 'mustard'], sizes: SIZES,
    desc_en: 'Fine, body-hugging knit, perfect under a jacket. Subtle chest customization.',
    desc_ar: 'قماش رفيع وضيّق، مثالي تحت السترة.' },
  { id: 'p4', cat: 'pull', name_en: 'Ribbed Knit Sweater', name_ar: 'بلوفر مضلّع',
    price: 5400, oldPrice: null, isNew: true, rating: 4.9, sold: 96,
    colors: ['cream', 'olive', 'rust', 'slate'], sizes: SIZES,
    desc_en: 'Warm, structured ribbed knit with a crew neck. Soft wool blend for cool evenings.',
    desc_ar: 'صوف مضلّع دافئ، ياقة دائرية.' },
  { id: 'p5', cat: 'pull', name_en: 'Roll-Neck Sweater', name_ar: 'بلوفر ياقة عالية',
    price: 5900, oldPrice: 6800, isNew: false, rating: 4.8, sold: 134,
    colors: ['sand', 'ink', 'forest', 'blush'], sizes: SIZES,
    desc_en: 'Cozy roll neck in a soft knit. An elegant, minimalist piece.',
    desc_ar: 'ياقة عالية ناعمة، قطعة أنيقة.' },
  { id: 'p6', cat: 'pull', name_en: 'Berber Jacquard Sweater', name_ar: 'بلوفر جاكار أمازيغي',
    price: 6500, oldPrice: null, isNew: true, rating: 5.0, sold: 58,
    colors: ['cream', 'clay', 'olive'], sizes: SIZES,
    desc_en: 'Jacquard patterns inspired by Berber rugs, woven into the knit. Limited edition.',
    desc_ar: 'نقوش جاكار مستوحاة من الزرابي الأمازيغية. إصدار محدود.' },
  { id: 'p7', cat: 'hoodie', name_en: 'Heavy Fleece Hoodie', name_ar: 'سويت بغطاء ثقيل',
    price: 6200, oldPrice: null, isNew: true, rating: 4.9, sold: 207,
    colors: ['ink', 'olive', 'clay', 'sand'], sizes: SIZES,
    desc_en: 'Brushed 380 gsm fleece, lined hood, kangaroo pocket. The ultimate canvas for your designs.',
    desc_ar: 'صوف داخلي 380غ/م²، غطاء مبطّن، جيب أمامي.' },
  { id: 'p8', cat: 'hoodie', name_en: 'Zip-Up Sport Hoodie', name_ar: 'سويت بسحّاب',
    price: 6800, oldPrice: 7500, isNew: false, rating: 4.7, sold: 143,
    colors: ['slate', 'ink', 'forest', 'navy'], sizes: SIZES,
    desc_en: 'Full zip, athletic cut, ribbed trims. Embroidered or printed logo, your choice.',
    desc_ar: 'سحّاب كامل، قصّة رياضية.' },
  { id: 'p9', cat: 'hoodie', name_en: 'Cropped Oversized Hoodie', name_ar: 'سويت أوفرسايز قصير',
    price: 5900, oldPrice: null, isNew: true, rating: 4.8, sold: 89,
    colors: ['blush', 'cream', 'olive', 'ink'], sizes: SIZES,
    desc_en: 'Short, wide trendy cut. Perfect for a large centered back print.',
    desc_ar: 'قصّة قصيرة وواسعة، عصرية.' },
  { id: 'p10', cat: 'tshirt', name_en: 'Long-Sleeve Tee', name_ar: 'تيشيرت أكمام طويلة',
    price: 3100, oldPrice: null, isNew: false, rating: 4.6, sold: 167,
    colors: ['cream', 'clay', 'navy', 'ink'], sizes: SIZES,
    desc_en: 'Thick long-sleeve cotton. Ideal surface to customize the sleeve.',
    desc_ar: 'قطن سميك بأكمام طويلة.' },
  { id: 'p11', cat: 'pull', name_en: 'Classic Crewneck Sweatshirt', name_ar: 'بلوفر سويت كلاسيك',
    price: 4600, oldPrice: null, isNew: false, rating: 4.7, sold: 254,
    colors: ['sand', 'olive', 'slate', 'ink'], sizes: SIZES,
    desc_en: 'Timeless crewneck sweatshirt in soft fleece. The perfect base to customize.',
    desc_ar: 'سويت شيرت كلاسيكي بياقة دائرية.' },
  { id: 'p12', cat: 'tshirt', name_en: 'Chest-Pocket Tee', name_ar: 'تيشيرت بجيب',
    price: 2600, oldPrice: null, isNew: true, rating: 4.5, sold: 73,
    colors: ['white', 'olive', 'clay', 'mustard'], sizes: SIZES,
    desc_en: 'Small patch pocket, refined detail. Back customization recommended.',
    desc_ar: 'جيب صغير أمامي، تفصيل أنيق.' },
];

// Demo orders for the admin dashboard.
const SEED_ORDERS = [
  { id: 'CMD-7341', name: 'Yacine Belkacem', phone: '0556 12 34 56', wilaya: '16 Alger', commune: 'Kouba',
    status: 'pending', date: '2026-06-02',
    items: [{ pid: 'p7', color: 'ink', size: 'L', qty: 1, custom: true, note: 'White logo on the back, A4 size. Please center it carefully.' }] },
  { id: 'CMD-7340', name: 'Amina Saïdi', phone: '0661 88 22 10', wilaya: '31 Oran', commune: 'Bir El Djir',
    status: 'prep', date: '2026-06-02',
    items: [{ pid: 'p1', color: 'clay', size: 'M', qty: 2, custom: false }] },
  { id: 'CMD-7339', name: 'Sofiane Mansouri', phone: '0770 45 67 89', wilaya: '25 Constantine', commune: 'El Khroub',
    status: 'shipped', date: '2026-06-01',
    items: [{ pid: 'p4', color: 'olive', size: 'L', qty: 1, custom: false }] },
  { id: 'CMD-7338', name: 'Lina Hamdi', phone: '0540 33 21 09', wilaya: '15 Tizi Ouzou', commune: 'Azazga',
    status: 'pending', date: '2026-06-01',
    items: [{ pid: 'p9', color: 'blush', size: 'S', qty: 1, custom: true, note: 'Print the name "Lina" in gold cursive on the right sleeve.' }] },
  { id: 'CMD-7337', name: 'Karim Boudiaf', phone: '0556 77 88 99', wilaya: '19 Sétif', commune: 'El Eulma',
    status: 'delivered', date: '2026-05-31',
    items: [{ pid: 'p8', color: 'forest', size: 'XL', qty: 1, custom: false }] },
  { id: 'CMD-7336', name: 'Nesrine Ould Ali', phone: '0661 10 20 30', wilaya: '06 Béjaïa', commune: 'Akbou',
    status: 'prep', date: '2026-05-31',
    items: [{ pid: 'p6', color: 'clay', size: 'M', qty: 1, custom: true, note: 'Small embroidered logo on left chest + large back design. Olive thread.' }] },
  { id: 'CMD-7335', name: 'Riad Cherif', phone: '0770 55 44 33', wilaya: '23 Annaba', commune: 'El Bouni',
    status: 'delivered', date: '2026-05-30',
    items: [{ pid: 'p2', color: 'ink', size: 'L', qty: 3, custom: false }] },
  { id: 'CMD-7334', name: 'Manel Brahimi', phone: '0540 99 88 77', wilaya: '09 Blida', commune: 'Boufarik',
    status: 'cancelled', date: '2026-05-30',
    items: [{ pid: 'p11', color: 'sand', size: 'M', qty: 1, custom: false }] },
];

module.exports = { SIZES, PRODUCTS, SEED_ORDERS };
